language: r
sudo: false
r: release

bioc_packages:
- phyloseq
- edgeR
- limma
- metagenomeSeq
- baySeq
- DESeq2
- ALDEx2
- impute

before_install:
- sudo apt-get install libgsl-dev

env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE